QOLOE-109 Print
qld-gov-au/qgds-qol-mvp pull request #164
Opened 2024-05-28 03:25 UTC by tedqgov

SWE Github print styles code: https://github.com/qld-gov-au/web-template-release

2024-05-28 03:53 UTC, ghazal-salehi commented
Just needs to resolve conflicts in above files.

2024-05-28 06:09 UTC, tedqgov commented
Okay, merge conflicts are resolved and pushed. Thanks @ghazal-salehi :)

2024-05-28 22:57 UTC, stvp-qld commented on .github/workflows/update.yml
Hi @tedqgov, just checking re this file. Did you make changes to this as part of your commit?

2024-06-03 01:14 UTC, stvp-qld requested changes
Hi @tedqgov, just checking re this file. Did you make changes to this as part of your commit?

2024-06-03 02:28 UTC, duttonw commented
please rebase this branch instead of merge develop in
git pull origin develop --rebase
at each conflict, review and fix then
git rebase --continue
after all is done, do a force push on this branch, it should only have your own commits all together.

2024-06-03 04:48 UTC, stvp-qld approved these changes

2024-06-03 05:02 UTC, tedqgov commented
> please rebase this branch instead of merge develop in git pull origin develop --rebase at each conflict, review and fix then git rebase --continue after all is done, do a force push on this branch, it should only have your own commits all together.

Yup, I've only rebased so far instead of merge develop.

2024-06-03 05:02 UTC, merged