QOLOE-13 Button
qld-gov-au/qgds-qol-mvp pull request #18
Opened 2024-03-26 06:50 UTC by tedqgov

Based on: https://www.design-system.health.qld.gov.au/components/buttons
Figma: https://www.design-system.health.qld.gov.au/components/buttons

2024-03-26 07:31 UTC, duttonw commented on storybook-static/assets/Blockquote.stories-1YB5jjwc.js
storybook-static should be auto genned on commit of develop/master and deployed to the gh-pages branch for auto display for you.

2024-03-26 07:34 UTC, duttonw commented on dist/assets/css/qld.bootstrap.css
please move to using a qgds-qol-mvp-bin or similar named folder for commiting the binary files so that this source repo stays super light. Since after a couple of years, the changes in the dist folder might be so great that the source/doc folders will be sub 1mb zipped but you will be waiting for 2gb to be cloned down due to all the minified files being kept around.

Please borrow  github action https://github.com/qld-gov-au/formio/blob/main/.github/workflows/compile.js.yml and https://github.com/qld-gov-au/formio/blob/main/.github/workflows/storybook-deploy.js.yml and alter to this projects build steps and binary/storybook folder names.

2024-03-26 07:36 UTC, duttonw reviewed
Have provided some inline comments, please try and move away from committing binary folders into the source repo and use a secondary git repo for your binary source control. Do borrow from https://github.com/qld-gov-au/formio/blob/main/.github/workflows/ to bootstrap this project to auto compile vs local compile only.

2024-03-27 03:49 UTC, stvp-qld commented on dist/assets/css/qld.bootstrap.css
Yes looking at options now.  We've setup qgds-qol-mvp-release for our compiled /dist assets and will link to this via the Squiz GitBridge.

2024-04-02 04:39 UTC, duttonw commented
this needs to be rebased and cleaned up in history for what needs to be altered for buttons.

2024-04-02 04:40 UTC, duttonw requested changes
needs to be rebased and updated if this is doing card or button PR.

2024-04-03 06:32 UTC, closed without merging